//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.AddInSideAdapters
{
    
    public class ISpeakerContractToViewAddInAdapter : Contracts.AddInViews.ISpeaker
    {
        private Contracts.ISpeaker _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static ISpeakerContractToViewAddInAdapter()
        {
        }
        public ISpeakerContractToViewAddInAdapter(Contracts.ISpeaker contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public string Say(Contracts.AddInViews.SayWhat what)
        {
            return _contract.Say(Contracts.AddInSideAdapters.SayWhatAddInAdapter.ViewToContractAdapter(what));
        }
        internal Contracts.ISpeaker GetSourceContract()
        {
            return _contract;
        }
    }
}

