//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class ISpeakerViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Contracts.ISpeaker
    {
        private Contracts.AddInViews.ISpeaker _view;
        public ISpeakerViewToContractAddInAdapter(Contracts.AddInViews.ISpeaker view)
        {
            _view = view;
        }
        public virtual string Say(Contracts.SayWhat what)
        {
            return _view.Say(Contracts.AddInSideAdapters.SayWhatAddInAdapter.ContractToViewAdapter(what));
        }
        internal Contracts.AddInViews.ISpeaker GetSourceView()
        {
            return _view;
        }
    }
}

