//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.AddInSideAdapters
{
    
    public class ISpeakerAddInAdapter
    {
        internal static Contracts.AddInViews.ISpeaker ContractToViewAdapter(Contracts.ISpeaker contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ISpeakerViewToContractAddInAdapter))))
            {
                return ((ISpeakerViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ISpeakerContractToViewAddInAdapter(contract);
            }
        }
        internal static Contracts.ISpeaker ViewToContractAdapter(Contracts.AddInViews.ISpeaker view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(ISpeakerContractToViewAddInAdapter)))
            {
                return ((ISpeakerContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ISpeakerViewToContractAddInAdapter(view);
            }
        }
    }
}

