//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.AddInSideAdapters
{
    
    public class SayWhatAddInAdapter
    {
        internal static Contracts.AddInViews.SayWhat ContractToViewAdapter(Contracts.SayWhat contract)
        {
            return ((Contracts.AddInViews.SayWhat)(contract));
        }
        internal static Contracts.SayWhat ViewToContractAdapter(Contracts.AddInViews.SayWhat view)
        {
            return ((Contracts.SayWhat)(view));
        }
    }
}

