//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.HostSideAdapters
{
    
    public class ISpeakerHostAdapter
    {
        internal static Contracts.HostViews.ISpeaker ContractToViewAdapter(Contracts.ISpeaker contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(ISpeakerViewToContractHostAdapter))))
            {
                return ((ISpeakerViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new ISpeakerContractToViewHostAdapter(contract);
            }
        }
        internal static Contracts.ISpeaker ViewToContractAdapter(Contracts.HostViews.ISpeaker view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(ISpeakerContractToViewHostAdapter)))
            {
                return ((ISpeakerContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new ISpeakerViewToContractHostAdapter(view);
            }
        }
    }
}

