//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts.HostSideAdapters
{
    
    public class SayWhatArrayHostAdapter
    {
        public static Contracts.HostViews.SayWhat[] ContractToViewAdapter(Contracts.SayWhat[] contract)
        {
            if ((contract == null))
            {
                return null;
            }
            Contracts.HostViews.SayWhat[] result = new Contracts.HostViews.SayWhat[contract.Length];
            for (int i = 0; (i < contract.Length); i = (i + 1))
            {
                result[i] = Contracts.HostSideAdapters.SayWhatHostAdapter.ContractToViewAdapter(contract[i]);
            }
            return result;
        }
        public static Contracts.SayWhat[] ViewToContractAdapter(Contracts.HostViews.SayWhat[] view)
        {
            if ((view == null))
            {
                return null;
            }
            Contracts.SayWhat[] result = new Contracts.SayWhat[view.Length];
            for (int i = 0; (i < view.Length); i = (i + 1))
            {
                result[i] = Contracts.HostSideAdapters.SayWhatHostAdapter.ViewToContractAdapter(view[i]);
            }
            return result;
        }
    }
}

